// Camera/lens combos to mimic real photography metadata
export const CAMERA_STYLES = [
  "shot on Canon EOS R5, 85mm f/1.4, natural lighting",
  "shot on Canon 5D Mark IV, 50mm f/1.2, ambient light",
  "shot on Canon EOS R6 II, 24-70mm f/2.8, mixed lighting",
  "shot on Sony A7IV, 35mm f/1.8, available light",
  "shot on Sony A7R V, 90mm f/2.8 macro, diffused light",
  "shot on Sony A6700, 18-135mm, outdoor natural light",
  "shot on Fujifilm X-T5, 56mm f/1.2, classic chrome simulation",
  "shot on Fujifilm X100VI, 23mm f/2, grain effect",
  "shot on Fujifilm GFX 100S, 80mm f/1.7, medium format",
  "shot on Nikon Z8, 50mm f/1.2, soft ambient light",
  "shot on Nikon Z6 III, 24-120mm f/4, overcast daylight",
  "shot on Nikon D850, 70-200mm f/2.8, telephoto compression",
  "Leica Q2, 28mm f/1.7, natural tones",
  "Leica M11, 50mm Summilux, rangefinder rendering",
  "iPhone 15 Pro, 24mm, ProRAW, computational HDR",
  "iPhone 16 Pro Max, 48mm, portrait mode, natural light",
  "Samsung Galaxy S24 Ultra, 200mm telephoto, AI enhanced",
  "Hasselblad X2D, 80mm f/1.9, medium format look",
  "Olympus OM-1, 45mm f/1.2, micro four thirds",
  "Pentax K-3 III, 77mm f/1.8 limited, warm color science",
  "Ricoh GR IIIx, 40mm f/2.8, snap aesthetic",
  "Panasonic S5 II, 50mm f/1.8, smooth video-like rendering",
];

export const NEGATIVE_PROMPT = "blurry, low quality, distorted, watermark, text, logo, cartoon, illustration, painting, drawing, render, CGI, plastic skin, extra fingers, deformed, artificial, fake looking";

export const PROMPTS: Record<string, string[]> = {
  people: [
      "professional headshot of a 40-year-old man in a navy blazer, soft window light, shallow depth of field, slightly off-center composition",
      "close-up portrait of a woman in her 30s with freckles, early morning golden hour, hair slightly windblown, genuine smile",
      "corporate headshot of a South Asian man in a charcoal suit, clean white background, studio strobe with softbox, crisp detail",
      "editorial portrait of an older Black woman with silver locs, dignified expression, dramatic Rembrandt lighting, dark background",
      "passport-style photo of a college student, neutral expression, flat flash, white wall behind, slightly awkward pose",
      "candid street portrait of a young woman walking through a European city, overcast day, 35mm film grain, looking away from camera",
      "environmental portrait of a carpenter in their workshop, sawdust in the air, warm tungsten light, medium shot",
      "elderly woman with silver hair sitting in a garden, reading glasses, dappled sunlight through leaves, content expression",
      "barista pulling espresso behind a counter, steam catching light, shallow depth of field, coffee shop interior",
      "farmer standing in front of a red barn at dawn, work boots, flannel shirt, hands on hips, mist in background",
      "nurse in scrubs taking a break outside a hospital, tired but kind eyes, overcast sky, candid moment",
      "fisherman mending nets at a dock, weathered hands, early morning light reflecting off water, tight crop",
      "group of coworkers having coffee outside an office building, natural expressions, mid-conversation, urban setting",
      "teenager skateboarding in a concrete park, frozen mid-trick, late afternoon backlight, motion blur on wheels",
      "chef preparing food in a professional kitchen, motion blur on hands, sharp face, overhead fluorescent light",
      "two friends laughing on a park bench, autumn leaves on ground, warm afternoon light, genuine moment",
      "street busker playing violin in a subway station, commuters blurred in background, overhead fluorescent mix with daylight",
      "children running through sprinklers in a backyard, frozen water droplets, summer afternoon, joy on faces",
      "yoga class in a sunlit studio, instructor demonstrating pose, mirrors reflecting natural light, peaceful atmosphere",
      "wedding guests on a dance floor, motion blur, colorful ambient lighting, candid celebration",
      "Indigenous elder with traditional jewelry, environmental portrait, desert landscape background, late afternoon sidelight",
      "Japanese grandmother making tea in a traditional room, tatami mats, soft window light, serene composition",
      "construction worker eating lunch on a steel beam, hard hat beside them, urban skyline background, midday sun",
      "librarian shelving books in an old library, dust motes in light beam from window, warm wood tones",
      "tattoo artist at work, close-up of gloved hands, buzzing machine, intense concentration, studio lighting",
      "woman in her 60s selling flowers at an outdoor market in Oaxaca, bright morning sun, colorful blooms framing her face",
      "young Black man in a tailored linen shirt, rooftop portrait at sunset, city skyline soft in background, warm rim light",
      "toddler taking first steps on a living room carpet, parent reaching out just behind, soft window light, candid joy",
      "middle-aged Korean woman tending a rooftop garden in Seoul, overcast afternoon, clay pots and green shoots, medium shot",
      "firefighter leaning against the engine after a call, soot on cheeks, late afternoon side light, exhausted relief",
      "university professor mid-lecture in a wood-paneled hall, chalkboard behind, warm overhead light, animated gesture",
      "elderly Sikh man with a white turban sitting outside a gurdwara in Amritsar, golden hour, dignified calm",
      "marathon runner crossing the finish line, sweat glistening, crowd blurred behind, overcast daylight, raw emotion",
      "girl in a school uniform reading under a banyan tree, Mumbai, dappled shade, afternoon heat",
      "mechanic sliding out from under a car on a creeper, grease-streaked coveralls, garage fluorescent light, low angle",
      "mother braiding her daughter's hair on a front porch, late afternoon golden light, shallow depth of field",
      "street food vendor flipping arepas on a griddle, Bogota sidewalk, steam rising, midday overcast",
      "cellist practicing alone in an empty concert hall, single spotlight, vast dark space behind, intense focus",
      "old man playing chess in Washington Square Park, winter coat, breath visible, overcast cold afternoon",
      "surfer walking out of the ocean at dawn carrying a board, wet suit, pink horizon, sand texture in foreground",
      "Maasai woman in traditional beadwork, Kenyan savanna background, late afternoon warm light, eye-level portrait",
      "baker dusted in flour pulling a tray from a stone oven, predawn shift, warm interior light spilling out",
      "couple sharing an umbrella on a rainy Parisian bridge, cobblestones wet, diffused grey light, candid moment",
      "physical therapist guiding a patient through exercises, bright clinical room, encouraging expression, natural light",
      "child blowing out birthday candles, warm tungsten glow on face, shallow depth of field, living room background",
      "bushy-bearded lumberjack splitting wood, Pacific Northwest forest clearing, morning mist, flannel sleeves rolled",
      "woman in her 50s painting at an easel in a sunlit attic studio, paint-stained apron, northern light from skylights",
      "young Latina woman laughing mid-conversation at a cafe table, iced coffee in front, warm afternoon, bokeh background",
      "gondolier rowing through a narrow Venice canal, striped shirt, late afternoon light bouncing off water",
      "retired couple walking a sandy beach at low tide, footprints trailing behind, soft overcast morning",
      "teenage girl adjusting telescope at a dark-sky observatory, red safety light, stars faintly visible, night portrait",
      "Peruvian shepherd with alpacas on a highland plateau, Andes peaks behind, late afternoon sidelight, wide shot",
      "jazz pianist mid-performance in a dimly lit club, sweat on brow, blue and amber stage light, close crop",
      "young father asleep on a couch with infant on his chest, soft lamp light, quiet domestic scene, overhead angle",
      "woman in a sari crossing a busy intersection in Jaipur, motion blur on passing rickshaws, midday sun",
      "blacksmith at a forge, orange glow on face, dark workshop behind, sparks frozen mid-flight",
      "boy selling fruit from a wooden cart on a dusty road, rural Vietnam, golden hour backlight, earnest expression",
      "dentist examining a patient, clinical overhead light, blue gloves, focused expression, tight medium shot",
      "grandmother kneading dough at a flour-dusted kitchen table, morning light from a single window, Tuscany farmhouse",
      "Thai monk walking barefoot on a dawn alms round, saffron robe, misty Chiang Mai street, warm soft light",
      "rock climber chalking up at the base of a sandstone wall, Moab Utah, harsh midday sun, upward angle",
      "two siblings sharing headphones on a city bus, afternoon commute light, candid closeness, shallow focus",
      "older Japanese man tending bonsai in a greenhouse, meticulous concentration, diffused overcast light, tight crop",
      "woman in scrubs and a hijab reviewing a chart in a hospital corridor, fluorescent light, purposeful stride",
      "potter shaping a bowl on a kick wheel, clay-wet forearms, studio skylight, motion blur on spinning clay",
      "street photographer crouched low on a Havana sidewalk, vintage camera to eye, warm Caribbean afternoon light",
      "boy casting a fishing line off a wooden dock, still lake at dawn, mist on water, peaceful solitude",
      "pair of ranch hands on horseback herding cattle, Montana grassland, dust cloud, golden late afternoon",
      "elderly woman arranging ikebana in a minimalist Japanese room, soft diffused light, precise composition",
      "young engineer in a hard hat inspecting a wind turbine base, flat Danish countryside, overcast sky, wide shot",
  ],
  animals: [
      "red fox standing in fresh snow, breath visible, early morning light, forest edge background",
      "barn owl perched on a weathered fence post, soft bokeh background, overcast day, UK countryside",
      "humpback whale breaching, water droplets frozen mid-air, overcast ocean, telephoto compression",
      "polar bear mother with two cubs walking across tundra, soft pink sunset light, Churchill Manitoba",
      "bald eagle in flight carrying a fish, river and forest below, sharp detail on feathers, Alaska",
      "grizzly bear fishing at a waterfall, salmon jumping, mist in air, Katmai National Park",
      "snow leopard on a rocky outcrop, camouflaged against grey stone, Himalayas, rare sighting",
      "pack of wolves trotting through deep snow, Yellowstone, breath visible, golden light, telephoto",
      "king penguin colony, thousands in frame, South Georgia Island, one standing in foreground sharp",
      "border collie mid-leap catching a frisbee, frozen motion, park setting, shallow depth of field",
      "tabby cat curled up on a worn leather armchair, afternoon sunbeam, dust motes visible",
      "golden retriever shaking off water at a lake, frozen droplets, backlit, summer afternoon",
      "black cat sitting on a windowsill, city lights bokeh behind, nighttime, green eyes glowing",
      "old beagle sleeping on a porch, warm light, wooden boards, peaceful summer evening",
      "horse and rider silhouetted against sunset, dust kicked up, ranch fence line, Western",
      "kitten playing with a ball of yarn on a hardwood floor, window light, curious expression",
      "monarch butterfly on a milkweed plant, macro shot, morning dew visible on wings",
      "sea otter floating on its back in kelp, Monterey Bay, eye-level water shot, whiskers in detail",
      "dragonfly perched on a reed, compound eyes in sharp detail, pond bokeh background, macro lens",
      "tree frog clinging to a wet leaf, vivid green skin, water droplets, Costa Rican cloud forest",
      "ladybug on a blade of grass, early morning dew drops, extreme macro, soft green background",
      "sea turtle swimming through crystal clear water, sunbeams from surface, coral reef below",
      "school of sardines forming a bait ball, diver silhouetted above, underwater photography, blue water",
      "clownfish in an anemone, macro underwater shot, vibrant orange against purple tentacles",
      "manta ray gliding overhead, shot from below, sun creating silhouette, Maldives",
      "African elephant matriarch leading her herd to a watering hole, Amboseli, Kilimanjaro hazy in background, golden hour dust",
      "cheetah mid-sprint across the Serengeti, legs fully extended, panning blur on grass, telephoto compression",
      "orangutan mother cradling an infant high in a Borneo rainforest canopy, dappled green light filtering through leaves",
      "blue heron standing motionless in a misty marsh at dawn, perfect reflection in still water, telephoto",
      "Bengal tiger drinking at a jungle pool, Ranthambore, reflection visible, late afternoon sidelight, dense foliage",
      "baby mountain gorilla peering through bamboo stalks, Volcanoes National Park Rwanda, overcast diffused light",
      "pair of Atlantic puffins on a grassy cliff ledge, Iceland, overcast sky, one with fish in beak",
      "red deer stag bellowing in autumn mist, Scottish Highlands, antlers silhouetted, breath visible, dawn",
      "flamingo flock wading in shallow alkaline lake, pink reflections, Lake Nakuru Kenya, aerial perspective",
      "arctic fox in winter coat trotting across frozen tundra, Svalbard, blue twilight, tracks in snow behind",
      "raccoon peeking out of a hollow tree trunk, suburban backyard, dusk, curious eyes catching last light",
      "koala sleeping in a eucalyptus fork, soft overcast light, fur texture in detail, Victoria Australia",
      "wild mustangs galloping across a sagebrush plain, Wyoming, dust cloud, late afternoon backlight, wide angle",
      "moose standing knee-deep in a misty lake, Maine, dawn light, water dripping from antlers, telephoto",
      "harbor seal pup resting on a rocky shore, big dark eyes, overcast coastal light, Monterey",
      "sandhill cranes in flight formation, Nebraska Platte River, sunrise sky, hundreds in frame, telephoto",
      "chameleon on a branch with tongue extended catching an insect, Madagascar, macro detail, vivid green",
      "young leopard draped over a tree branch, Kruger National Park, spotted coat in dappled shade, relaxed",
      "pelican diving into water for fish, splash frozen mid-impact, Gulf Coast, bright midday sun",
      "corgi puppy running through fallen autumn leaves, park path, ears flopping, joyful expression, eye level",
      "Siamese cat stretching on a sun-warmed tile floor, Mediterranean villa, afternoon light, elegant pose",
      "baby elephant playing in mud, Amboseli, trunk spraying water, joyful energy, warm afternoon light",
      "snowy owl perched on a fence post, Canadian prairie, flat white landscape, overcast winter sky, piercing yellow eyes",
      "hermit crab on wet sand at low tide, macro detail on shell, Caribbean beach, warm morning light",
      "hummingbird hovering at a red flower, wings frozen mid-beat, iridescent throat feathers, garden setting",
      "wolf spider carrying babies on her back, forest floor leaf litter, extreme macro, morning dew",
      "hippo yawning in a river, massive jaws open, Masai Mara, late afternoon, water level perspective",
      "sleeping barn cat on a hay bale, shaft of dusty light through barn door, rustic warmth, tight crop",
      "giant Pacific octopus moving across a rocky reef, tentacles in motion, underwater ambient light, British Columbia",
      "white-tailed deer fawn hidden in tall grass, spots visible, soft overcast light, Appalachian meadow",
      "macaw pair perched on a branch, vivid scarlet and blue feathers, Amazonian canopy, diffused light",
      "jellyfish pulsing through dark water, bioluminescent glow, translucent bell, Monterey Bay aquarium lighting",
      "Australian shepherd herding sheep across a green hillside, morning fog, rural New Zealand, action shot",
      "kingfisher emerging from water with a fish, splash frozen, UK riverbank, fast shutter, vibrant plumage",
      "iguana basking on a sun-baked rock, Galapagos, rough textured skin in sharp detail, volcanic backdrop",
      "mother duck leading a line of ducklings across a pond, lily pads, morning light, suburban park",
      "grey whale surfacing to breathe, barnacled skin detail, Baja California, calm sea, telephoto from boat",
      "red panda curled on a mossy branch, Sichuan bamboo forest, overcast light, fluffy tail wrapped around body",
      "bumblebee covered in pollen inside a sunflower, macro detail, summer garden, warm backlight",
      "Galápagos tortoise lumbering across volcanic terrain, ancient wrinkled skin, low angle, overcast sky",
      "peregrine falcon perched on a city ledge, urban skyline behind, dawn light, sharp predator gaze",
      "coyote trotting through a snowy field at dusk, Wyoming, purple twilight, breath visible, telephoto",
      "starfish clinging to a tidal rock, low tide pools, Pacific Northwest coast, overcast, macro detail",
      "pair of swans forming a heart shape on a misty lake, dawn, English countryside, telephoto, soft light",
      "giraffe silhouetted against a vast African sunset, acacia tree in frame, Serengeti, telephoto compression",
  ],
  food: [
      "sourdough loaf with deep ear scoring on a wire cooling rack, rustic wooden counter, flour dusted, side lighting",
      "croissants fresh from the oven, flaky layers visible, baking sheet, steam rising, bakery kitchen",
      "artisan bread display at a farmers market, various shapes and crusts, morning sunlight, hand-written labels",
      "cinnamon rolls with cream cheese icing dripping, cast iron skillet, rustic table, overhead shot",
      "steaming bowl of tonkotsu ramen, soft-boiled egg halved, chashu pork, chopsticks resting on bowl edge, overhead shot",
      "hand-rolled sushi on a hinoki wood board, ginger and wasabi, natural daylight from left, 45-degree angle",
      "dim sum bamboo steamers stacked, har gow and siu mai, tea pot, Chinese restaurant table, warm light",
      "Thai green curry in a clay bowl, jasmine rice, fresh basil garnish, banana leaf underneath, Bangkok street food",
      "Korean bibimbap in a hot stone bowl, egg yolk unbroken on top, vegetables arranged in sections, sizzling edges",
      "wood-fired margherita pizza on a peel, charred crust bubbles, San Marzano tomatoes visible, steam rising",
      "stack of blueberry pancakes with melting butter pat, syrup mid-pour, diner setting, warm light",
      "molten chocolate fondant on a white plate, powdered sugar dusted, raspberry coulis swoosh, restaurant plating",
      "charcuterie board with aged cheeses, cured meats, figs, honey, crackers, marble surface, overhead",
      "grilled ribeye steak medium rare, cross-section visible, cast iron pan, herb butter melting, smoke rising",
      "lobster roll overflowing with chunks, buttered split-top bun, paper tray, New England waterfront background",
      "farmers market display of heirloom tomatoes, various colors and sizes, morning sun, overhead perspective",
      "bowl of fresh berries with morning dew, white ceramic, linen napkin, natural window light, close-up",
      "spice market stall with pyramids of colorful ground spices, brass scoops, warm ambient light, Morocco",
      "olive oil being poured onto a caprese salad, motion freeze, tomatoes and mozzarella, garden table",
      "latte art being poured, rosetta pattern forming in cup, barista hands visible, coffee shop counter",
      "craft cocktail with smoke bubble on top, bar counter, moody low lighting, copper tools behind",
      "matcha being whisked in a ceramic bowl, bamboo chasen, Japanese tea ceremony, overhead angle",
      "fresh orange juice in glass pitcher, sliced oranges, bright morning kitchen, condensation on glass",
      "red wine being poured into a glass, vineyard sunset behind, Tuscany, golden backlight through wine",
      "shakshuka bubbling in a cast iron skillet, runny eggs in spiced tomato sauce, torn bread on the side, morning table",
      "bowl of pho with thin-sliced beef, bean sprouts, and Thai basil, steam rising, chopsticks lifting noodles, Hanoi street stall",
      "fresh-baked baguette broken open revealing airy crumb structure, linen towel, rustic French kitchen, morning light",
      "plate of jerk chicken with rice and peas, charred skin glistening, scotch bonnet on the side, Jamaican roadside cookout",
      "stack of fluffy Japanese souffle pancakes, dusted with powdered sugar, pat of butter melting on top, cafe table in Tokyo",
      "tagine being opened at a Marrakech riad, steam escaping, preserved lemons visible, candlelit dinner table",
      "crispy fish tacos with slaw and lime crema, paper-lined basket, Baja California beachside, harsh noon sun",
      "bowl of handmade pasta with brown butter and sage, parmesan shavings, rustic Italian trattoria, warm interior light",
      "chocolate chip cookies cooling on a sheet pan, gooey centers, one broken in half, home kitchen afternoon light",
      "oysters on crushed ice with lemon wedges and mignonette, raw bar counter, cool blue-white light, overhead",
      "Ethiopian injera platter with colorful wots, berbere-stained edges, communal plate, Addis Ababa, warm tungsten",
      "pork belly bao buns on a bamboo steamer, pickled cucumber, hoisin drizzle, Taipei night market glow",
      "avocado toast on sourdough with poached egg, runny yolk, everything bagel seasoning, brunch table, window light",
      "fresh mozzarella being stretched by hand, cheese pull visible, Naples kitchen, warm tungsten light, action shot",
      "paella in a wide shallow pan, saffron rice, prawns, mussels, lemon wedges, Valencia outdoor table, afternoon sun",
      "bowl of Tom Yum Goong with prawns, lemongrass, and kaffir lime leaves, Bangkok street stall, steam catching light",
      "peking duck carved tableside, lacquered skin glistening, thin pancakes and scallion, Beijing restaurant, warm light",
      "tiramisu slice on a white plate, cocoa powder dusted, visible layers of mascarpone and coffee-soaked ladyfingers",
      "charcoal-grilled corn on the cob being brushed with butter, Mexican street vendor, smoke rising, evening light",
      "fresh ceviche in a glass bowl, diced fish with red onion and cilantro, lime wedges, Lima oceanfront",
      "Georgian khachapuri with molten cheese and a raw egg in the center, bread boat shape, rustic wooden table",
      "Neapolitan ice cream in a waffle cone, three colors dripping slightly, summer boardwalk, bright midday sun",
      "Vietnamese banh mi being assembled, crusty baguette, pickled daikon, cilantro, pate, Saigon street cart",
      "smoked brisket being sliced, bark crust and pink smoke ring visible, butcher paper, Texas BBQ joint",
      "Greek salad with chunky feta, Kalamata olives, and ripe tomatoes, outdoor taverna table, Aegean Sea behind, noon light",
      "fresh-caught trout sizzling in a cast iron pan over a campfire, pine forest clearing, dusk, golden embers",
      "bowl of açai topped with granola, sliced banana, and drizzled honey, bright Rio de Janeiro morning, close-up",
      "Argentinian empanadas fresh from the oven, crimped edges golden, chimichurri in a small bowl, rustic board",
      "plate of eggs Benedict with hollandaise dripping, crispy Canadian bacon, brunch restaurant, soft morning light",
      "tempura prawns and vegetables arranged on washi paper, tentsuyu dipping sauce, Japanese izakaya, warm light",
      "churros dusted with cinnamon sugar, thick hot chocolate for dipping, Madrid cafe counter, late morning",
      "butter chicken in a copper serving dish, naan bread alongside, basmati rice, Indian restaurant, warm amber light",
      "platter of freshly shucked clams with drawn butter, newspaper-lined table, New England clam shack, overcast afternoon",
      "pomegranate cut open showing ruby seeds, white marble surface, diffused north-facing window light, tight crop",
      "waffles with whipped cream and fresh strawberries, powdered sugar falling mid-air, Belgian cafe, morning",
      "plate of pierogi with caramelized onions and sour cream, Polish kitchen table, winter afternoon window light",
      "mango sticky rice on a banana leaf, coconut cream drizzle, Bangkok market stall, warm evening light",
      "wood-smoked salmon fillet on a cedar plank, flaky texture, dill garnish, Pacific Northwest outdoor table",
      "bowl of gazpacho with olive oil swirl and croutons, terracotta bowl, Andalusian summer patio, bright light",
      "dumplings being pleated by hand, flour-dusted wooden surface, Shanghai kitchen, overhead perspective, soft light",
      "cheesecake slice with glossy berry compote, fork cutting through creamy layer, cafe plate, afternoon",
      "lamb shank braised until falling off the bone, creamy polenta underneath, red wine reduction, candlelit bistro",
      "granola scattered across a baking sheet fresh from the oven, clusters with dried fruit, honey drizzle, kitchen light",
      "street vendor ladling hot mulled wine into a mug, cinnamon sticks and star anise floating, Christmas market, steam, dusk",
      "grilled halloumi slices with char marks on a salad of arugula and roasted beets, lemon dressing, overhead angle",
      "hand pulling apart a warm pretzel, salt crystals visible, mustard pot nearby, German biergarten, afternoon",
  ],
  landscapes: [
      "misty valley at dawn, layers of fog between forested ridges, Appalachian mountains, no sky visible",
      "jagged alpine peaks with fresh snow, dramatic cloud shadows sweeping across the face, Dolomites, early morning",
      "volcanic crater lake with emerald water, steam vents on the rim, overcast sky, wide angle, New Zealand",
      "rolling green hills dotted with sheep, stone walls dividing pastures, Lake District England, soft overcast",
      "mountain meadow with wildflowers in bloom, snow-capped peaks behind, Colorado Rockies, golden hour",
      "rocky coastline at low tide, tide pools in foreground, overcast sky, long exposure smoothed waves",
      "turquoise glacial river winding through black volcanic sand, Iceland aerial perspective, overcast",
      "mangrove roots at low tide, reflection in still water, tropical humidity haze, Florida Keys",
      "dramatic cliff face meeting the ocean, seabirds in flight, stormy sky, Cliffs of Moher, Ireland",
      "frozen waterfall with blue ice formations, long icicles, winter forest background, Minnesota",
      "calm lake at sunrise, perfect mirror reflection, lone canoe at dock, Boundary Waters, mist rising",
      "single dirt road cutting through golden wheat fields, flat horizon, cumulus clouds, Midwest USA",
      "desert canyon with layered red sandstone walls, narrow slot canyon, beam of light from above, Antelope Canyon",
      "cracked dry lakebed stretching to mountains, heat shimmer, Alvord Desert Oregon, late afternoon",
      "sand dunes at blue hour with star trails beginning, Sahara, single set of footprints leading away",
      "vast sunflower field at peak bloom, farmhouse in distance, Kansas, golden afternoon light",
      "dense moss-covered forest floor, fallen logs, Pacific Northwest rainforest, diffused overcast light",
      "bamboo grove with light filtering through, path winding between stalks, Arashiyama Kyoto, morning mist",
      "autumn forest canopy from below, looking straight up, red and orange leaves backlit by sun, Vermont",
      "ancient sequoia trunk filling the frame, person at base for scale, forest cathedral light, California",
      "birch forest in winter, white trunks against fresh snow, minimal composition, soft grey sky, Finland",
      "frozen lake at twilight, cracked ice patterns, distant snow-capped peaks reflected, Iceland",
      "terraced rice paddies filled with water reflecting sunset, Bali, aerial perspective",
      "lightning bolt striking a distant mesa, dark storm clouds, desert foreground, long exposure, Arizona",
      "northern lights reflecting in a fjord, green and purple aurora, snow-covered shores, Norway",
      "granite sea stack at sunset, crashing waves at the base, Oregon coast, warm sidelight on wet rock",
      "glacial moraine lake with milky turquoise water, loose scree foreground, Canadian Rockies, overcast afternoon",
      "tidal flats at low tide, rippled sand patterns stretching to horizon, Mont Saint-Michel bay, silver light",
      "peat bog with cotton grass in bloom, dark pool in foreground, Scottish Highlands, soft drizzle",
      "karst limestone pinnacles rising from jungle, mist clinging to the bases, Guilin China, dawn light",
      "chalk cliffs eroding into the sea, white rubble on the beach, Seven Sisters England, flat grey sky",
      "volcanic lava field with fresh green ferns emerging, steam vents, Big Island Hawaii, overcast morning",
      "prairie grassland under massive cumulonimbus buildup, Oklahoma, late afternoon, storm approaching",
      "fjord from a high overlook, cruise ship tiny below, steep green walls, Geirangerfjord Norway, midday",
      "muddy river delta seen from above, branching channels, sediment plumes, Bangladesh, monsoon season",
      "lichen-covered boulders on a windswept moor, low clouds dragging across the hilltop, Dartmoor England",
      "frozen river cutting through taiga forest, fresh snowfall on spruce trees, Siberia, blue twilight",
      "salt flats stretching to vanishing point, thin layer of water creating mirror effect, Salar de Uyuni, Bolivia",
      "wildfire smoke turning the sun blood-red over a mountain lake, hazy layers, British Columbia, eerie calm",
      "coastal wetland with wading birds, sawgrass, still water, Everglades Florida, humid overcast dawn",
      "high desert plateau with scattered juniper trees, red earth, distant thunderstorm, northern New Mexico",
      "ice-choked arctic shoreline, pancake ice and brash ice, flat horizon, grey sky, Svalbard, summer",
      "blooming lavender rows converging toward a lone oak tree, Provence France, late afternoon warm light",
      "deep gorge with a ribbon waterfall, black basalt walls, spray catching light, Blue Mountains Australia",
      "tundra in autumn color, low shrubs turning crimson, distant caribou, Denali Alaska, overcast",
      "wave crashing over a seawall during a winter storm, spray frozen in air, English Channel, dramatic",
      "river bend through old-growth forest, fallen tree bridging the banks, Olympic Peninsula, soft rain",
      "savanna at golden hour, scattered acacia trees, long shadows, Serengeti Tanzania, dust haze",
      "glacial tongue reaching toward a grey proglacial lake, lateral moraines, Patagonia, windy overcast",
      "mountain pass road switchbacks seen from above, autumn color on slopes, Stelvio Pass Italy, afternoon",
      "coral pink sand dunes under a cloudless blue sky, sparse desert scrub, southern Utah, midday",
      "lake shore with polished stones in shallow water, clear to the bottom, Lake Superior, morning calm",
      "cloud forest canopy from a ridge, clouds filling the valley below, Monteverde Costa Rica, humid morning",
      "snow-covered volcano cone reflected in a still lake, perfect symmetry, Mount Fuji Japan, winter dawn",
      "sea of clouds filling a valley, mountain peaks as islands, Swiss Alps, sunrise, pink and gold light",
      "dry stone wall running across moorland, heather in bloom, purple hillside, Yorkshire Dales, overcast",
      "turquoise hot spring pool with mineral deposits on the rim, Yellowstone, steam rising, winter morning",
      "coastal fog burning off over a rocky headland, wildflowers in foreground, Big Sur California, mid-morning",
      "flooded forest floor in spring, cypress knees protruding, mirror-still water, Louisiana bayou, dawn",
      "wind-sculpted sandstone hoodoos in a tight cluster, orange and cream bands, Bryce Canyon Utah, late light",
      "alpine meadow after a rain shower, water droplets on grass, rainbow fragment, Austrian Tyrol, afternoon",
      "mangrove-lined river at high tide, kayak in distance, calm water, Yucatan Mexico, hazy tropical light",
      "barren lava field meeting the ocean, black rock and white surf, Lanzarote Canary Islands, overcast",
      "old-growth temperate rainforest draped in hanging moss, nurse log with saplings, Vancouver Island, fog",
      "steppe grassland under enormous open sky, single dirt track, Mongolia, cumulus clouds casting shadows",
      "waterfall plunging into a plunge pool, mist rising, tropical vegetation framing, Iguazu Falls, midday",
      "rocky desert wash after a flash flood, muddy water rushing, dark clouds clearing, Death Valley, dusk",
      "pebble beach with perfectly rounded stones, gentle waves, overcast, Lake Baikal Russia, autumn",
      "plantation of tea bushes in neat rows on a hillside, picker in distance, Sri Lanka hill country, morning mist",
      "eroded badlands striped in bands of grey and rust, no vegetation, Drumheller Alberta, harsh midday sun",
  ],
  architecture: [
      "brutalist concrete apartment block, geometric repeating balconies, flat overcast sky, shot from street level",
      "modern glass office tower reflecting sunset clouds, shot from below with converging verticals",
      "Frank Gehry curved titanium panels, Bilbao, overcast sky reflecting in surface, wide angle",
      "minimalist concrete church interior, single beam of light from skylight, Tadao Ando style",
      "contemporary wooden cabin cantilevered over a hillside, floor-to-ceiling glass, forest setting, dusk",
      "Dubai Marina towers at blue hour, reflections in water, long exposure light trails on road",
      "gothic cathedral nave interior, ribbed vaults, late afternoon light through rose window, no people",
      "narrow cobblestone alley in Lisbon, azulejo tile facades, hanging laundry, warm afternoon light",
      "art deco cinema entrance, neon marquee, terrazzo floor, evening blue hour, symmetrical composition",
      "traditional Japanese machiya townhouse, wooden lattice facade, Kyoto backstreet, diffused light",
      "Venetian palazzo reflected in canal, weathered pink stucco, green shutters, morning light, gondola passing",
      "half-timbered medieval buildings lining a market square, Colmar France, flower boxes, overcast afternoon",
      "Moorish archways with intricate tile work, Alhambra Granada, courtyard with reflecting pool",
      "abandoned textile mill, broken windows, vines growing through brick, moody overcast, wide angle",
      "rusting steel bridge over a river, industrial city backdrop, foggy morning, muted tones",
      "overgrown greenhouse, shattered glass panels, plants reclaiming the space, golden light filtering through",
      "Detroit abandoned theater, ornate plasterwork crumbling, single shaft of light from collapsed roof",
      "spiral staircase from directly above, geometric pattern, marble steps, ornate iron railing",
      "mid-century modern living room, Eames chair, warm afternoon light, record player, minimal clutter",
      "old wooden bookshop interior, floor to ceiling shelves, rolling ladder, warm lamp light, Oxford",
      "train station concourse, vaulted iron and glass ceiling, morning rush commuters blurred, Grand Central",
      "Buddhist temple at dawn, gold leaf details catching first light, incense smoke, Chiang Mai Thailand",
      "ancient Roman aqueduct stretching across a valley, sunset behind, Segovia Spain, dramatic scale",
      "white-washed Greek Orthodox church with blue dome, Santorini, deep blue Aegean Sea behind, noon sun",
      "Angkor Wat reflected in lotus-filled moat, dawn, temple silhouette, Cambodia, pink and purple sky",
      "Bauhaus apartment facade, clean white render and steel balconies, Tel Aviv, harsh midday sun, geometric shadows",
      "covered timber bridge interior, worn plank floor, filtered light through gaps, rural Vermont, autumn outside",
      "row of painted Victorian houses, pastel colors, steep street, early morning fog, San Francisco",
      "concrete parking garage interior, fluorescent strips, oil stains on floor, single parked car, brutalist geometry",
      "crumbling adobe mission church, exposed wooden beams, desert scrub around base, New Mexico, late afternoon",
      "modern museum atrium with floating concrete stairway, visitors below for scale, overcast skylight, Osaka",
      "ornate Baroque ceiling fresco seen from directly below, gilded stucco frames, church interior, Vienna",
      "fishing village row of wooden houses on stilts over water, weathered paint, overcast sky, Lofoten Norway",
      "abandoned Soviet-era swimming pool, cracked tiles, empty diving platform, weeds growing, urban exploration mood",
      "Romanesque cloister with paired columns, herb garden in courtyard, warm stone, southern France, soft afternoon",
      "cantilevered glass observation deck over a canyon, vertigo perspective looking down, cloudy sky, Skywalk style",
      "industrial grain elevator cluster, corrugated steel, railway siding, flat prairie behind, overcast, Saskatchewan",
      "traditional Rajasthani haveli courtyard, carved sandstone screens, blue walls, Jodhpur India, midday light",
      "art nouveau metro entrance, wrought iron and glass canopy, green patina, drizzle, Paris, morning",
      "library reading room with vaulted painted ceiling, long oak tables, green desk lamps, late afternoon sun",
      "stone-walled trullo houses with conical roofs, whitewashed, olive grove behind, Alberobello Italy, noon",
      "modernist chapel with stained glass wall casting colored light on concrete floor, Le Corbusier style, Ronchamp",
      "derelict Ferris wheel against overcast sky, peeling paint, empty gondolas, Pripyat exclusion zone",
      "terraced hillside town, pastel stucco buildings stacked up the slope, Positano Amalfi Coast, golden hour",
      "covered market hall interior, cast iron columns, skylights, produce stalls below, Barcelona, morning",
      "shipping container housing complex, stacked and painted, urban infill lot, Copenhagen, overcast afternoon",
      "wooden stave church with dragon-head gable carvings, dark tarred timber, green valley setting, Borgund Norway",
      "rooftop water towers silhouetted against a pink sunset sky, brick apartment buildings, Manhattan, telephoto compression",
      "Ottoman-era hammam interior, domed ceiling with star-shaped skylights, steam, warm stone, Istanbul",
      "weathered New England lighthouse on a rocky point, whitecapped sea behind, grey sky, autumn",
      "underground cistern with rows of columns reflected in still water, dim artificial light, Istanbul Basilica Cistern",
      "colonial shophouse row, louvered shutters, tiled five-foot way, tropical plants, Georgetown Penang, afternoon",
      "monolithic concrete dam face, water cascading over spillway, mist rising, forested gorge, overcast",
      "abandoned railway station waiting room, arched windows, peeling paint, pigeons roosting, golden dust-filled light",
      "ziggurat-style stepped university library, exposed concrete, students on terraces, overcast, brutalist 1960s",
      "narrow medieval lane with overhead stone arches, worn cobbles, laundry hanging, Dubrovnik Croatia, shade and light",
      "glass and steel greenhouse conservatory, tropical palms inside, condensation on panes, Kew Gardens London, grey sky",
      "Pueblo Revival adobe house, vigas protruding, flat roof with parapet, Taos New Mexico, warm late-afternoon light",
      "opera house interior from the upper balcony, red velvet seats, ornate gilding, empty stage, chandelier lit",
      "corrugated iron warehouse converted to art space, exposed trusses, polished concrete floor, Johannesburg",
      "stepped well descending into darkness, geometric repeating stairs, Rajasthan India, harsh overhead sun",
      "suspension bridge cables in fog, steel towers disappearing upward, pedestrians below, overcast morning",
      "thatched-roof cottage with stone walls, wildflower garden, Cotswolds England, soft summer overcast",
      "high-rise construction site, exposed rebar and formwork, tower crane, workers in hard hats, overcast, Hong Kong",
      "neo-Gothic university quadrangle, ivy on stone walls, manicured lawn, Oxford, autumn afternoon light",
      "prefab Scandinavian cabin with green roof, birch trees, lakeside, soft overcast, minimal and clean",
      "ancient amphitheater carved into a hillside, stone seats, stage ruins, afternoon shadows, Epidaurus Greece",
      "Mughal fort ramparts in warm sandstone, arched openings framing a dusty plain, Jaipur India, golden hour",
      "dilapidated pier extending into calm grey water, wooden pilings exposed, seabirds perching, overcast winter",
      "Japanese torii gate standing in shallow sea water, low tide, wet sand, Miyajima Island, dawn, pink sky",
  ],
  art: [
      "oil painting of a stormy North Sea in an ornate gilded frame, gallery wall with spot lighting",
      "visitor standing in front of a massive Rothko color field painting, museum scale, contemplative",
      "Dutch Golden Age still life with fruit and flowers, dramatic chiaroscuro, ornate frame, museum wall",
      "Impressionist landscape in a sunlit gallery, visitors reflected in protective glass, Musee d'Orsay",
      "contemporary abstract painting, thick impasto texture, artist studio wall, paint-splattered floor",
      "large Cor-Ten steel sculpture in a sculpture garden, autumn trees background, overcast sky",
      "marble bust in a museum, Bernini style, dramatic side lighting, dark background, extreme detail",
      "neon light installation in a dark gallery, pink and blue reflections on polished floor",
      "kinetic sculpture with hanging mobile elements, museum atrium, natural light from above, Calder style",
      "ice sculpture melting in a gallery, water pooling beneath, impermanence captured, cold blue light",
      "vibrant street mural covering a three-story brick wall, spray paint texture visible, urban setting",
      "Banksy-style stencil on a crumbling wall, political commentary, monochrome with one color accent",
      "yarn bombing on a city bridge railing, colorful knitted covers, overcast urban setting, playful",
      "wheat paste portrait on a construction hoarding, peeling edges, rain-dampened, city sidewalk",
      "potter's wheel with wet clay being shaped, hands in frame, studio with natural skylight",
      "printmaker pulling an etching from a press, ink on hands, workshop with hanging prints drying",
      "glassblower shaping molten glass, orange glow, dark workshop, intense heat visible, action shot",
      "weaver at a large floor loom, colorful threads, natural light from side window, concentrated expression",
      "blacksmith hammering red-hot metal, sparks flying, dark forge, dramatic contrast",
      "stained glass window detail, lead came visible, backlit by overcast sky, interior view, medieval church",
      "Japanese zen rock garden, raked gravel patterns, mossy boulders, temple wall behind, Ryoanji",
      "large scale charcoal drawing pinned to a studio wall, graphite smudges, artist tools on table below",
      "ceramic collection on wooden shelves, earth-toned glazes, studio with northern light, hand-made quality",
      "bronze casting workshop, lost-wax molds, patina chemicals, industrial space, work in progress",
      "terracotta warrior replica in a museum case, dramatic uplighting, Beijing, dust motes in air",
      "Renaissance fresco detail on a vaulted ceiling, scaffolding partially visible, restoration in progress, Florence",
      "woodcut print drying on a clothesline in a printmaking studio, black ink on white washi paper, soft daylight",
      "mosaic floor fragment in an archaeological museum, tiny colored tesserae, protective glass, overhead view",
      "outdoor sculpture park in winter, snow draped on abstract steel forms, bare trees, overcast, Storm King",
      "calligrapher grinding ink on a stone slab, brush resting on a bamboo rest, rice paper ready, quiet studio",
      "art student sketching a plaster cast in a drawing class, easels around, charcoal on paper, warm studio light",
      "gallery opening night, visitors studying a video installation, projected light on faces, white cube space",
      "massive earthwork land art seen from aerial perspective, spiral jetty form, Great Salt Lake, overcast",
      "indigenous Australian dot painting on bark, ochre and white pigments, museum display, spot lit",
      "sculptor chiseling marble block, stone chips on floor, dust in light beam, workshop in Carrara Italy",
      "antique daguerreotype in an open velvet case, tarnished silver plate, period portrait visible, museum",
      "graffiti-covered freight train car in a rail yard, layered tags and throws, overcast, industrial setting",
      "blown glass vessels in a gallery vitrine, colored light passing through, white pedestal, clean exhibition",
      "tapestry hanging on a stone castle wall, faded medieval hunting scene, diffused window light, Loire Valley",
      "outdoor chalk art on rain-dampened pavement, artist kneeling beside it, pastels in a box, urban plaza",
      "wire sculpture of a human figure suspended from gallery ceiling, shadow cast on white wall, minimal",
      "batik cloth being dipped in indigo dye vat, artisan in rubber gloves, Java Indonesia, workshop light",
      "illuminated manuscript page under museum glass, gold leaf and mineral pigments, detail of marginalia",
      "plein air painter at an easel on a cliff edge, seascape before them, wind in their hair, Cornwall England",
      "contemporary ceramic installation covering a gallery wall, hundreds of small forms, white on white, dramatic shadows",
      "woodworker hand-planing a walnut board, shavings curling, workbench with chisels, warm tungsten light",
      "letterpress type drawer, lead letters sorted in compartments, inky rollers nearby, old print shop",
      "paper-cutting artist at a table, intricate silhouette emerging, X-Acto blade, northern light from window",
      "mural restoration in progress, conservator on scaffolding with cotton swabs, before-and-after visible, church wall",
      "totem pole in a cedar forest clearing, moss on the base, carved and painted figures, Haida Gwaii, overcast",
      "lithography stone being inked with a roller, workshop with presses, overhead fluorescent light, art school",
      "Venetian mask workshop, painted masks on wall hooks, gold leaf and feathers, artisan at bench, warm light",
      "gallery corridor of Old Master paintings, parquet floor, bench in center, visitor in distance, warm spotlights",
      "sand mandala being created by monks, colored sand flowing from metal funnels, close detail, temple floor",
      "encaustic wax painting being heated with a torch, surface melting and pooling, rich textures, studio close-up",
      "raku pottery being pulled from a kiln with tongs, glowing orange, smoke from sawdust reduction, night firing",
      "large format photograph mounted on aluminum in a Chelsea gallery, viewer close enough to see print grain",
      "tintype photograph developing in a chemical bath, dark tent, hands in gloves, wet plate process, outdoor fair",
      "light painting photograph on a long exposure, swirling streaks in a dark field, single figure holding the source",
      "shibori fabric hung to dry, deep indigo with white resist patterns, clothesline in a Japanese courtyard",
      "fresco secco technique, pigment being applied to dry plaster wall, artist on a low scaffold, Mexican mural tradition",
      "museum conservation lab, painting face-down on a table, X-ray image on a screen, technician with white gloves",
      "outdoor fire sculpture at night, flame paths in steel channels, crowd watching from a distance, festival setting",
      "linocut printing block with gouged design, ink roller beside it, test pull on paper, studio table",
      "silver gelatin darkroom print in a developer tray, image emerging, red safelight, chemical trays in a row",
      "stone inlay work in progress, marble and semi-precious pieces, artisan with magnifying loupe, Agra India",
      "site-specific installation of suspended thread, thousands of lines filling a room, light from windows creating pattern",
      "copper etching plate being acid-bitten, bubbles forming on surface, printmaker watching, ventilated workshop",
      "artist studio wall covered in pinned reference photos, sketches, paint swatches, creative chaos, north-facing skylight",
      "gallery hung salon-style floor to ceiling, ornate gold frames, visitor on a bench, old European museum",
  ],
  street: [
      "rain-slicked city street at night, neon signs reflecting in puddles, lone pedestrian with umbrella, Tokyo",
      "food cart with steam rising, night market, string lights overhead, customers waiting, Taipei",
      "empty subway platform at 2am, fluorescent lights, lone commuter on a bench, tile walls, New York",
      "jazz club exterior, red neon sign, bouncer at door, cigarette smoke, wet sidewalk, New Orleans",
      "convenience store glowing on a dark street corner, figure walking past, urban isolation, Edward Hopper mood",
      "Shibuya crossing from above, rush hour, motion blur on pedestrians, sharp buildings, overcast",
      "street musician playing upright bass on a Paris metro platform, motion blur of passing train, warm tungsten",
      "market stall overflowing with colorful spices, vendor weighing on brass scale, Istanbul",
      "cyclist splashing through a puddle on a cobblestone street, frozen water droplets, Amsterdam",
      "newspaper stand vendor in morning light, stacks of papers, coffee cup, early risers passing",
      "outdoor cafe in Rome, espresso cups on small tables, locals reading newspapers, morning light",
      "fish market at dawn, ice and fresh catch, workers in rubber boots, harsh fluorescent overhead, Tokyo Tsukiji",
      "fruit vendor arranging display on a sidewalk, pyramids of mangoes and papayas, Mumbai",
      "vintage car parked on an empty desert highway, heat shimmer, vanishing point composition, Route 66",
      "yellow taxi in rain, Times Square reflections, motion blur, night, iconic New York moment",
      "steam rising from a manhole cover on a cold morning, city sidewalk, pedestrians walking through, atmospheric",
      "ferry crossing a choppy harbor, city skyline behind, overcast, seagulls, Istanbul Bosphorus",
      "bicycle leaning against a canal railing, autumn leaves on ground, Amsterdam, soft overcast light",
      "tram rounding a corner on cobblestones, overhead wires, Lisbon, steep hill, pastel buildings",
      "umbrella crowd at a busy intersection, monsoon rain, Mumbai, reflections everywhere, overhead shot",
      "snow falling on a quiet residential street, warm window glow from houses, footprints, dusk, Scandinavia",
      "heat haze rising from asphalt, desert gas station, lone figure, American Southwest, noon sun",
      "fog rolling down a San Francisco hill, Victorian houses emerging, car headlights, early morning",
      "autumn leaves blowing across an empty park path, wrought iron bench, golden light, Central Park",
      "night bus interior, lone passenger, fluorescent glow, rain streaking the windows, London double-decker",
      "laundromat at night, warm interior light spilling onto sidewalk, washing machines spinning, figure folding clothes",
      "old man feeding pigeons on a park bench, winter coat, flat overcast light, city square, Prague",
      "children playing soccer in a dusty alley, low afternoon sun, long shadows, Havana Cuba",
      "motorbike loaded with goods weaving through traffic, motion blur on surroundings, Hanoi Vietnam, midday",
      "underground pedestrian tunnel, tiled walls, single commuter walking toward the light, overhead fluorescent, Moscow",
      "flower seller arranging bouquets on a street corner, buckets of blooms, morning light, Paris",
      "rush hour commuters descending into a metro station, overhead shot, coats and bags, autumn, Seoul",
      "cobblestone plaza at dawn, empty except for a street sweeper, wet stones, first light on buildings, Krakow Poland",
      "late-night diner counter, single customer and a cook, warm overhead light, chrome and vinyl, American Midwest",
      "rickshaw puller resting in shade, midday sun on the street, Kolkata India, worn sandals, quiet moment",
      "street barber under a tree, mirror hung on the trunk, customer in a chair, Addis Ababa Ethiopia, warm light",
      "pigeons scattering from a city sidewalk, frozen mid-flight, pedestrian flinching, overcast, London",
      "gondolier navigating a narrow canal, stone walls on both sides, dappled afternoon light, Venice backstreet",
      "rooftop clotheslines strung between buildings, colorful laundry, blue sky above, Naples Italy, looking up",
      "early morning jogger on an empty boardwalk, ocean to one side, mist, sunrise behind, Brighton England",
      "woman carrying water jugs on her head, dusty road, acacia tree in background, East Africa, golden hour",
      "skateboarder grinding a rail, frozen mid-trick, graffitied underpass, overcast, Berlin",
      "elevated train passing over a busy street, pedestrians below, steel structure shadow, Chicago Loop, midday",
      "horse-drawn carriage on a wet cobblestone street, evening lamplight, old quarter, Marrakech Morocco",
      "monks in saffron robes collecting morning alms, mist, quiet street, Luang Prabang Laos, dawn",
      "delivery cyclist checking a phone at a stoplight, insulated bag on back, drizzle, London evening",
      "puddle on a potholed road perfectly reflecting a building facade, post-rain, quiet side street, Buenos Aires",
      "person sheltering under an awning during a downpour, wet neon sidewalk, Osaka Japan, night",
      "stray dog sleeping on warm pavement, afternoon sun, quiet lane, Athens Greece, crumbling wall behind",
      "commuters on a crowded escalator, motion blur, deep underground station, warm tungsten lighting, Moscow metro",
      "tai chi practitioners in a park at dawn, slow motion implied, misty trees behind, Shanghai",
      "boy flying a kite from a rooftop, city skyline behind, blue sky with clouds, Lahore Pakistan, afternoon",
      "florist shop front spilling onto the sidewalk, buckets of tulips and peonies, Amsterdam, soft morning rain",
      "night fisherman casting a line from a city pier, harbor lights behind, calm water, Marseille France",
      "market alley strung with bare lightbulbs, produce crates stacked high, evening, Amman Jordan",
      "pedestrian waiting at a crosswalk in heavy snowfall, headlights approaching, quiet downtown, Sapporo Japan",
      "mechanic working under a raised car, oil-stained concrete, workshop open to the street, Beirut Lebanon, midday",
      "couple sharing a bench in a small urban garden, autumn trees, fallen leaves, soft overcast, Kyoto",
      "newspaper delivery truck stopped on an empty predawn street, bundled papers, streetlamp glow, small town America",
      "window washer on a suspended platform high above the street, tiny figures below, glass and steel, Hong Kong",
      "packed commuter train platform, doors about to close, harried passengers, overhead fluorescent, Mumbai local",
      "street cat perched on a windowsill above a busy lane, geraniums in a planter, afternoon light, Dubrovnik Croatia",
      "vendor roasting chestnuts over a barrel fire, smoke and steam, winter evening, Rome, warm orange glow",
      "deserted beach boardwalk in off-season, closed shutters on food stands, grey sky, Atlantic City, melancholy",
      "morning mist on a canal, houseboats with glowing windows, cyclist on the towpath, Amsterdam, dawn",
      "grandmother sweeping the front steps of a townhouse, early morning, broom and apron, Havana Cuba, warm light",
      "parking lot at dusk, sodium vapor lamps flickering on, scattered cars, puddles from earlier rain, suburban USA",
      "funicular climbing a steep hill, cityscape widening behind, passengers in the cabin, Valparaiso Chile, afternoon",
      "roadside tea stall with plastic chairs, steaming kettle, truck parked nearby, Punjab India, golden late-afternoon dust",
      "empty basketball court under a single floodlight, chain-link fence, city blocks in background, night, Brooklyn",
  ],
};

export function pickPrompt(category: string): string | null {
  const prompts = PROMPTS[category];
  if (!prompts) return null;
  return prompts[Math.floor(Math.random() * prompts.length)];
}

export function cameraStyle(): string {
  return CAMERA_STYLES[Math.floor(Math.random() * CAMERA_STYLES.length)];
}

export function randomCategory(): string {
  const cats = Object.keys(PROMPTS);
  return cats[Math.floor(Math.random() * cats.length)];
}
